# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build main site

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

#    runs-on: ubuntu-18.04
    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Setup wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build wasm dependency
      run: npm run build:wasm
#    - name: Generate meta
#      run: npm run gen_meta
  
    - name: Install node packages
      run: yarn install --immutable --immutable-cache --check-cache
    - name: Build
      run: yarn build
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
    
    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.MONA_SSH_KEY }}
        SOURCE: dist/
        REMOTE_HOST: ${{ secrets.MONA_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.MONA_REMOTE_USER }}
        TARGET: ${{ secrets.MONA_TARGET }}
    
#     - name: Rename dist folder
#       run: mv dist dist_no_ignore
#     - name: Commit dist
#       uses: stefanzweifel/git-auto-commit-action@v4
#       with:
#         commit_message: "ci: Update build result"
#         branch: dist_main
#         create_branch: true
#         push_options: "--force"
